insightsengineering/teal

- NEWS.md
- R/module_nested_tabs.R
- R/module_teal.R
- inst/js/init.js
- tests/testthat/test-module_nested_tabs.R
- tests/testthat/test-module_tabs_with_filters.R
- vignettes/creating-custom-modules.Rmd
closes #676 
So I find out the there is some reactivity from FilteredData, which cases the modules to be CREATED MANY
TIMES from scratch. The fIlter_spec shows us a side effect of it, the filter was reinitialized each time.
We could play here with isolate, still out primary decision was to revert it in such case.
> revert - full input cycle

- DESCRIPTION
- README.md
- tests/testthat/test-get_rcode.R
part of https://github.com/insightsengineering/teal/issues/668
Also closes https://github.com/insightsengineering/teal/issues/686
> DESC and README

- DESCRIPTION
- R/module_nested_tabs.R
- R/modules.R
- man/module.Rd
Closes #683 along with
- https://github.com/insightsengineering/teal.slice/pull/73
- https://github.com/insightsengineering/teal.transform/pull/86
NOTE: this does not solve https://github.com/insightsengineering/teal.slice/issues/58 which I think we should attack soon (but will involve some work in teal.data as well)
Edit: Also closes #698
> pass join keys object into the module

- R/include_css_js.R
- R/module_teal.R
Update font awesome icon labels for FA 6, to avoid warnings like:
```
This Font Awesome icon ('some icon') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
be deactivated with `verify_fa = FALSE`
```
> Update font awesome icon labels for FA 6

- DESCRIPTION
- NEWS.md
- R/module_teal.R
This fixes the first part of https://github.com/insightsengineering/teal/issues/752
Requires https://github.com/insightsengineering/teal.widgets/pull/100
Test with:
```
library(teal)
app <- init(
data = teal_data(
dataset("MTCARS", mtcars)
),
modules = modules(example_module())
)
shinyApp(app$ui, app$server)
```
> Add sessionInfo

- tests/testthat/test-module_nested_tabs.R
- tests/testthat/test-rcode_utils.R
Fixes test failure on the environment where packages loads in a different order. We can't expect that the environment everywhere will have the same packages versions and thus the same dependencies. There is high chance that packages will be loaded in different order (according to dependency tree). This is why we can't fix the order of packages but test has to be "dynamic"
> Fix failing test

- NEWS.md
- R/example_module.R
- R/get_rcode.R
- R/init.R
- R/module_nested_tabs.R
- R/module_tabs_with_filters.R
- R/module_teal_with_splash.R
- R/modules_debugging.R
- man/example_module.Rd
- man/filter_calls_module.Rd
- man/init.Rd
- man/module.Rd
- man/modules_depth.Rd
- man/srv_nested_tabs.Rd
- man/srv_tabs_with_filters.Rd
- man/srv_teal.Rd
- man/srv_teal_with_splash.Rd
- man/ui_nested_tabs.Rd
- man/ui_tabs_with_filters.Rd
- tests/testthat/test-init.R
- vignettes/adding-support-for-reporting.Rmd
- vignettes/creating-custom-modules.Rmd
- vignettes/including-adam-data-in-teal.Rmd
- vignettes/including-general-data-in-teal.Rmd
- vignettes/including-mae-data-in-teal.Rmd
- vignettes/preprocessing-data.Rmd
- vignettes/teal-bs-themes.Rmd
- vignettes/teal.Rmd
refers to https://github.com/insightsengineering/nestdevs-tasks/issues/3
fix checks so that we fail instead of just return false that is not used at all
> convert check to assert

- DESCRIPTION
- NEWS.md
- R/module_nested_tabs.R
- man/dot-datasets_to_data.Rd
- tests/testthat/test-module_nested_tabs.R
closes #803 
Solution 2 to solve the reactivity of teal apps:
1) Transformed `srv_nested_tabs.teal_module` into `moduleServer`
2) Added a NULL `renderUI` in `srv_nested_tabs.teal_module` to trigger the filtered data when the tab is changed
3) Updated `.datasets_to_data` to accept a `reactiveVal` trigger function to refresh the filtered data
4) Updated and added a couple of tests
Please test with exploratory app or similar apps.
> teal reactivity solution 2

- R/get_rcode.R
- R/get_rcode_utils.R
- tests/testthat/test-rcode_utils.R
This is an answer to #835 
Before the change
After the change
> 835 - get_rcode_*() starts new code chunks in newlines

- R/teal_filters.R
this fixes https://github.com/insightsengineering/teal.slice/issues/330
Here in this PR , parameter module_add is being added to teal::teal_filters() which passes parameter value to teal.slice::filter_settings() function. 
Testing code:
```
options(teal.log_level = "TRACE", teal.show_js_log = TRUE)
library(shiny)
library(scda)
library(scda.2022)
library(teal.data)
library(teal.transform)
library(teal.modules.general)
pkgload::load_all()
funny_module <- function (label = "Filter states", datanames = "all") {
checkmate::assert_string(label)
module(
label = label,
filters = datanames,
ui = function(id, ...) {
ns <- NS(id)
div(
h2("The following filter calls are generated:"),
verbatimTextOutput(ns("filter_states")),
verbatimTextOutput(ns("filter_calls")),
actionButton(ns("reset"), …
```
> 330 [Feature Request]: Option to not show module_add

- vignettes/adding-support-for-reporting.Rmd
Closes #818 
With this PR we aimed to explain `teal.code` usage in `Adding support for Reporting to custom modules` vignette. This vignette demonstrates the usage of `teal.reporter` modules with `teal` apps. The example with `teal.code` is not necessary for the vignette however it shows an advanced combination of usage of `teal.code` and `teal.reporter` hence I decided not to remove `teal.code` snippets from this article.
There are also `teal.code` snippets in another vignette (`Creating Custom Modules`), so removal from this one would not remove the Suggests dependency for the `teal.code` package anyway.
I also reviewed the text and tried to polish it. 
Lastly, there examples in `R/module_tabs_with_filters.R` were updated during  https://github.com/insightsengineering/teal/issues/870
> 818 documentation cleanup

- R/module_filter_manager.R
- R/module_snapshot_manager.R
- vignettes/adding-support-for-reporting.Rmd
Fixes #867 
Fixes #878 
The mapping matrix is modified to display filters that cannot be applied to a particular module as NA.
In `matrix_to_mapping` filters that are NA are treated as TRUE because global filters may not apply to some modules.
Requires a new public method in `FilteredData`, introduced [here](https://github.com/insightsengineering/teal.slice/pull/408).
> 867 modify mapping matrix

- R/init.R
`teal.slice::teal_slices` doesn't initialize filters as it doesn't have `global_filters` specified.
```r
library(shiny)
library(scda)
library(scda.2022)
library(teal.data)
library(teal.transform)
pkgload::load_all("teal.slice")
pkgload::load_all("teal")
library(teal.modules.general)
funny_module <- function(label = "Filter states", datanames = "all") {
checkmate::assert_string(label)
module(
label = label,
datanames = datanames,
ui = function(id, ...) {
ns <- NS(id)
div(
h2("The following filter calls are generated:"),
verbatimTextOutput(ns("filter_states")),
verbatimTextOutput(ns("filter_calls")),
actionButton(ns("reset"), "reset_to_default")
)
},
server = function(input, output, session, data, filter_panel_api) {
checkmate::assert_class(data, "tdata")
observeEvent(input$reset, …
```
> handling initial teal_slice

- R/module_filter_manager.R
- R/module_snapshot_manager.R
- inst/css/sidebar.css
Fixes #883 
Placeholder signs are added to filter manager and snapshot manager for cases when no filters/snapshots are present.
> add placeholders to managers

- R/teal_slices.R
- man/teal_slices.Rd
Related to [this issue](https://github.com/insightsengineering/teal.slice/issues/410).
> 410 note experimental

- NEWS.md
- R/module_filter_manager.R
- R/modules.R
- R/reporter_previewer_module.R
Fixes #910 
The column named `"Report previewer"` is removed from the mapping matrix display.
Since the data.frame sent to `renderTable` potentially has one less column, the `align` argument is modified accordingly.
Additionally, `"Report previewer"` has been reserved as a module label during module creation, much like `"global_filters"`.
Since the actual previewer is supposed to have that label, it is set after the module is created.
This will only work as long as the name `"Report previewer"` does not change.
> 910 Remove Report Previewer column

- R/ddl-run.R
The` .substitute_inputs` function substitute value for inputs either input$ or input[[, but problem occurs when variable names that contain periods or hyphens, such as `var.name `or` var-name` Although such variable names are unconventional but they are acceptable . To ensure that the `.substitute_inputs `function can work with a wider range of variable names, I have made adjustments to the regular expressions within the function so that it can correctly recognize and handle them. This will allow for adherence to R's flexible naming conventions without causing any errors during the substitution process.
for test regular expression
```
code_strings <- c("open_conn(username = input$username, username = input$use.rname, password = input$`pass-word`)",
"open_conn(username = …
```
> adding regular expression to parse some edge cases.

- DESCRIPTION
- NEWS.md
- R/get_rcode_utils.R
- R/init.R
- R/module_nested_tabs.R
- R/module_teal.R
- R/module_teal_with_splash.R
- R/utils.R
- man/get_datasets_code.Rd
- man/init.Rd
- man/teal_data_to_filtered_data.Rd
- tests/testthat/test-module_nested_tabs.R
- tests/testthat/test-module_tabs_with_filters.R
- tests/testthat/test-module_teal_with_splash.R
Preprocessing code is no longer kept in `FilteredData$code` but attached to a `FilteredData` as an attribute.
Necessary adjustments were made in `teal_data_to_filtered_data` and in `get_datasets_code`.
[companion](https://github.com/insightsengineering/teal.slice/pull/488)
> 471 remove `CodeClass` from `FilteredData`

- .pre-commit-config.yaml
- README.md
Related with #949, updating the link to `reporoster` in README.
Also updated the pre-commit config to include `teal.code`.
> update repo roster link and pre-commit config

- R/dummy_functions.R
Modified `example_module` to remove `data` argument from UI function. Data set selection is moved to a `renderUI` element on the server side.
> update example module

- vignettes/creating-custom-modules.Rmd
* adapted to `teal_data` class
* generalized example module
* dropped mentions of `teal.transform`
> vignette custom modules

- R/teal_slices-store.R
- tests/testthat/test-teal_slices-store.R
Closes #1000 
Hey, I fixed the issue with disability to load a snapshot with empty `selected` field.
This filter can now be created, saved and uploaded.
However on an upload of such filter and selection of such filter the app goes back to empty filters. Is that intended?
> 1000 fix empty selection in restore

- tests/testthat/test-module_nested_tabs.R
Fixes https://github.com/insightsengineering/teal.slice/issues/502
Part of https://github.com/insightsengineering/teal.slice/pull/503 and https://github.com/insightsengineering/teal.data/pull/215
- Corrects test to reflect behavior resulting from `teal.data` default parent setting when creating new `join_key`
> Modifies tests as filter result uses a parent-child relationship by default

- DESCRIPTION
- tests/testthat/test-module_nested_tabs.R
- tests/testthat/test-report_previewer_module.R
- tests/testthat/test-tdata.R
- tests/testthat/test-teal_reporter.R
- tests/testthat/test-utils.R
Part of https://github.com/insightsengineering/coredev-tasks/issues/430
> 430 use `expect_no_error` in tests instead of `expect_error(, NA)`

- inst/css/custom.css
Fixes #1063
Background is blur before user agree to the disclaimer:
> add css to blur out background when using landing popup module

- inst/css/custom.css
Closes #1078 
Modified CSS to restore right padding in `body` when modal is not open.
Solution found [here](https://stackoverflow.com/questions/32862394/bootstrap-modals-keep-adding-padding-right-to-body-after-closed).
> 1078 padding added

- NEWS.md
- R/init.R
- R/module_teal_with_splash.R
- man/init.Rd
- vignettes/data-as-shiny-module.Rmd
> 1076 reorder formals

- vignettes/teal-options.Rmd
Closes #1066 
Changes:
1. Verified the current options we support.
- ✅ teal (`teal.load_nest_code`, `teal.show_js_log`, `teal.bs_theme`)
- ✅ teal.logger (`teal.log_level`)
- ✅ teal.widgets (`teal.basic_table_args`, `teal.ggplot2_args`, `teal.plot_dpi`)
- ✅ teal.slice (`teal.threshold_slider_vs_checkboxgroup`)
- ❌ teal.modules.general (`ggplot2.discrete.colour`)
- ❌ teal.modules.clinical (`ggplot2.discrete.colour`, `tmc_default_total_label`)
2. Removed the context of where the options were implemented, it seems unnecessary.
3. Reordered the options in the way that important and most used are at the top and are grouped when possible. And, moved the depreciated options to the bottom.
> Update the options vignette

- DESCRIPTION
- NEWS.md
- R/init.R
- R/tdata.R
- README.md
- inst/WORDLIST
- man/teal-package.Rd
- tests/testthat/test-tdata.R
- vignettes/getting-started-with-teal.Rmd
> [skip vbump] upversion to 0.15.0

- R/init.R
- man/init.Rd
Fixes #1132
* Enables module specific filters in `init` example
* note: vignettes already use it when there's a mapping
> Enables module-specific filters on `init` example

- R/TealAppDriver.R
Part of [#503](https://github.com/insightsengineering/coredev-tasks/issues/503)
There's no need to store "app" from `super$initialize`
> Removes redundant `app` from R6 class

- R/TealAppDriver.R
- man/TealAppDriver.Rd
I found it handy to have a function like this in here https://github.com/insightsengineering/teal/pull/1127#issuecomment-1994283810
Proposing a method to exist at `TealAppDriver` directly.
> 503 `$active_module_element` method for `TealAppDriver`

- R/TealAppDriver.R
We often just use our methods to pass parameters directly to other methods of `TealAppDriver` or `AppDriver` directly. Those already can have `{checkmate}`-like assertions on parameters' classes. However we tend to do operations on our parameters (mostly pasting) before we use them further. Now a big teal, but I would suggest checking if the input has a proper value before we paste it and pass forward. The length and the class.
> 503 add `{checkmate}` assertions to `TealAppDriver`

- R/TealAppDriver.R
- man/TealAppDriver.Rd
- tests/testthat/test-shinytest2-init.R
- tests/testthat/test-shinytest2-modules.R
- tests/testthat/test-shinytest2-reporter.R
- tests/testthat/test-shinytest2-utils.R
So instead of `app$get_html(selector) %>% rvest::read_html()` we can shortly write `app$read_html(selector)`.
> 503 `$get_html_rvest` method for `TealAppDriver`

- R/TealAppDriver.R
Fixes #1197
- Adds the `shinytest2` double colon prefix
> Adds double colon prefix to `platform_variant()`

- R/TealAppDriver.R
Part of https://github.com/insightsengineering/coredev-tasks/issues/503
- [feature] Wait for app to be idle by default (skips if `wait = FALSE` parameter is passed)
- [fix] Removes 5s waiting on every `app_driver$click()`
- It was waiting for UI to be stable for 5s, instead of setting the timeout.
- Current default timeout is set on constructor at 20s
> Tests wait for idle by default after setting module input

- R/TealAppDriver.R
- man/TealAppDriver.Rd
- man/reporter_previewer_module.Rd
> 1203 rename `TealAppDriver$set_module_input` to `TealAppDriver$set_active_module_input`

- R/TealAppDriver.R
- tests/testthat/test-shinytest2-filter_panel.R
- tests/testthat/test-shinytest2-teal_slices.R
Related to #1195 
I'm focusing on `test-shinytest2-filter_panel` to gain more insight during the integration test.
- Use alternative method of checking visibility of element when `el.checkVisibility()` method does not exists (is `null`)
- Fix tests that were relying on the order of unordered filters (categorical)
- `expect_setequal` instead of `expect_equal` to compare vectors.
> Fixes integration tests when Chrome >=105 is not installed

- R/TealAppDriver.R
Fixes the broken [shinytest2 tests](https://github.com/insightsengineering/teal/actions/runs/8961636987/job/24609457272)
The root cause is that `numeric_version` only accepts character to convert into `numeric_version` class. So typecasting of the numeric version was giving the error.
Example code to test. This works in older R versions. But, in R 4.4.0 it does not work.
```r
numeric_version('123') > 120
#Works
numeric_version('123') > '120'
```
> Fix shinytest2 app init on R 4.4.0+

- DESCRIPTION
Update the DESCRIPTION with the least dependant `teal.reporter` version.
> vbump the `teal.reporter` dependency

- R/TealAppDriver.R
- man/TealAppDriver.Rd
- man/teal_slices.Rd
Extend the `get_active_module_tws_output` to also work for `DT::DTOutput` which is now renamed to `get_active_module_table_output` along with `get_active_module_plot_output`
Example to test:
```r
devtools::load_all("../teal")
library(teal.modules.clinical)
data <- teal_data()
data <- within(data, {
ADSL <- teal.data::rADSL
ADLB <- teal.data::rADLB
})
datanames <- c("ADSL", "ADLB")
teal.data::datanames(data) <- datanames
teal.data::join_keys(data) <- teal.data::default_cdisc_join_keys[datanames]
app_driver <- TealAppDriver$new(
data = data,
modules = tm_t_pp_laboratory(
label = "Vitals",
dataname = "ADLB",
patient_col = "USUBJID",
paramcd = teal.transform::choices_selected(
choices = teal.transform::variable_choices(data[["ADLB"]], "PARAMCD"),
selected = "PARAMCD"
),
param = …
```
> Extend the table fetcher to handle DT tables too

- R/show_rcode_modal.R
- man/show_rcode_modal.Rd
> 1154 deprecation for `show_rcode_modal`

- R/TealAppDriver.R
- man/TealAppDriver.Rd
Introduces a private method for `TealAppDriver` called `wait_for_page_stability` which blocks the R process by sleeping until the page is unchanged till the stability period.
This is used in two places:
1. After a click is performed.
2. Before the visibility is checked.
This should potentially fix the CI errors in tmg and tmc.
Error in tmg:
```r
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-shinytest2-tm_misssing_data.R:73:3'): e2e - tm_missing_data: Default settings and visibility of the summary graph ──
Error in `app_wait_for_idle(self, private, duration = duration, timeout = timeout)`: An error occurred while waiting for Shiny to be stable
Backtrace:
▆
1. └─app_driver$click(selector = app_driver$active_module_element("iris-filter_na")) …
```
> A method to check for page stability when shiny is not busy

- R/TealAppDriver.R
Closes https://github.com/insightsengineering/coredev-tasks/issues/554
Changes:
1. ~The container in the integration test does not seem to evaluate the JS code to check visibility when `app_driver$is_visible` is called with `visibility_property = TRUE`~ Bumping the chrome version to resolve this issue.
2. Increasing the timeout threshold for `wait_for_page_stability`. For an unknown reason this timeout does not work in certain containers. Initial timeout (500ms) was set as a 2x of what was needed in my local machine. But looks like we need at least 800 ms to work in some loaded conditions. So, setting it to 2000 ms now.
> Fix the integration tests by alternative 

- R/module_teal.R
- man/module_teal.Rd
Fixes https://github.com/insightsengineering/teal/issues/1225
> `module_teal` documentation update

- R/1.0_module_data_summary.R
```r
❯ checking R code for possible problems ... NOTE
get_object_filter_overview_MultiAssayExperiment : get_experiment_keys:
no visible binding for global variable 'colname'
srv_data_summary : <anonymous>: no visible binding for global variable
'obs'
srv_data_summary : <anonymous>: no visible binding for global variable
'obs_filtered'
srv_data_summary : <anonymous>: no visible binding for global variable
'subjects'
srv_data_summary : <anonymous>: no visible binding for global variable
'subjects_filtered'
Undefined global functions or variables:
colname obs obs_filtered subjects subjects_filtered
```
is a part of a NOTE https://github.com/insightsengineering/teal/actions/runs/9954607649/job/27500608846#step:24:103
that is on CHECK GitHub Action blocklist …
> Fix R CMD Notes for `Undefined global functions or variables:`

- R/1.0_module_data_summary.R
- R/TealAppDriver.R
- man/TealAppDriver.Rd
- tests/testthat/test-module_data_summary.R
- tests/testthat/test-module_teal.R
- tests/testthat/test-shinytest2-data_summary.R
A couple of tests for `data_summary` panel. Knowing that namespace can get changed based on the final decision of the UI/UX placement of the new `data_summary` panel we need to be aware that those methods and tests might need to be updated. Currently trying to provide some more testing for the panel
> `{shinytest2}` and `shiny::testServer` tests for `data_summary` panel

- .github/workflows/scheduled.yaml
https://github.com/insightsengineering/teal/actions/runs/10262416165
> add refs to rhub workflow

- tests/testthat/test-module_teal.R
- tests/testthat/test-shinytest2-data_summary.R
- tests/testthat/test-shinytest2-teal_data_module.R
Added tests to check the two new features of the `teal_data_module`:
1. Now `teal_data_module` can have `once` argument.
2. The module tabs are disabled when `teal_data_module` is not loaded.
> Adds tests to check the new features of teal_data_module

- R/module_data_summary.R
- R/module_teal_data.R
- R/utils.R
Part of #1253
Additionally, we could have a static message on the summary, instead of repeating it.
Simple change with
```diff
diff --git a/R/module_data_summary.R b/R/module_data_summary.R
index 76947d58a..dadfff0dc 100644
--- a/R/module_data_summary.R
+++ b/R/module_data_summary.R
@@ -89,7 +89,7 @@ srv_data_summary <- function(id, teal_data) {
output$table <- renderUI({
summary_table_out <- try(summary_table())
if (inherits(summary_table_out, "try-error")) {
-          stop(strip_style(conditionMessage(attr(summary_table_out, "condition"))))
+          stop("Data and/or filters have an error. See details on main panel.")
} else {
body_html <- apply(
summary_table_out,
```
> Removes string colors style from error messages in `ui/srv_validate_reactive_teal_data`

- R/module_teal.R
- inst/css/custom.css
Have a fixed position for the icons in the top right which do not change place when the number of teal tab grows.
> Always position the teal util icons in the same place

- DESCRIPTION
follow-up after #1253
tests are failing using the released version
> vbump deps

- R/init.R
- R/module_init_data.R
- R/module_nested_tabs.R
- R/module_teal_data.R
- R/teal_data_module.R
- R/teal_data_utils.R
- R/utils.R
This simplifies a code in teal a little bit.
Instead of using `.teal_data_datanames` function which checks if `data@datanames` is specified and either get `data@datanames` or `ls(data@env)`,
here we set `data@datanames` if unspecified and always refer to `data@datanames`
What it changes is that in `teal_transform_module` when evaluated, `data` passed to its server, will always have `datanames` specified.
> Set @datanames in teal if unspecified

- .github/workflows/check.yaml
- R/module_nested_tabs.R
- R/module_teal.R
- R/module_teal_data.R
- tests/testthat/test-module_teal.R
- tests/testthat/test-shinytest2-filter_panel.R
This PR extends #1333 
Starting a new PR against the feature branch in case my changes break pipelines. The current feature branch is green and working. The only thing we wanted to improve is the reduction of the repetitive code and inclusion of such code into modules.
@gogonzo the last thing to discuss is whether we rename `srv_validate_teal_data` or `srv_validate_reactive_teal_data`. Maybe this discussion can be continued in here https://github.com/insightsengineering/teal/pull/1330#discussion_r1738646780
<details><summary>Tested with below code</summary>
```r
pkgload::load_all("teal")
app <- init(
data = teal_data(iris_raw = iris, mtcars = mtcars),
modules = modules(example_module("Module 1"), example_module("Module 2"))
)
shinyApp(app$ui, app$server)
app <- init(
data = …
```
> 1304 extensions - wrap repetitive code into modules

- R/modules.R
- tests/testthat/test-modules.R
`module()$datanames` are affected by `datanames` parameter and `datanames` coming out of `transformers`.
So far this is not unified, and the outcome `$datanames` depend on the length of input of the transformers. 
They are different if the transformer has length 1. 
```r
example_module("mod-1", transformers = 
list(
), 
datanames = c("ADSL", "ADTTE"))$datanames
example_module("mod-1", transformers = 
list(
teal_transform_module(ui = function(id) NULL, server = function(id, data) NULL)
), 
datanames = c("ADSL", "ADTTE"))$datanames
[1] "all" 
example_module("mod-1", transformers = 
list(
teal_transform_module(ui = function(id) NULL, server = function(id, data) NULL),
teal_transform_module(ui = function(id) NULL, server = function(id, data) NULL)
), 
datanames = c("ADSL", "ADTTE"))$datanames …
```
> `module()$datanames` : unify `combined_datanames` no matter what's the length of `transformers`

- R/module_teal_lockfile.R
- R/zzz.R
- tests/testthat/setup-options.R
- tests/testthat/test-init.R
Part of https://github.com/insightsengineering/teal/pull/1263 and closes https://github.com/insightsengineering/teal/issues/1276
Local results of `shinytest2` tests
```r
══ Results ══════════════════════════════════════════════════════════════════════════
Duration: 540.8 s
── Skipped tests (6) ────────────────────────────────────────────────────────────────
• need a fix in a .slicesGlobal (1): test-module_teal.R:1139:11
• todo (5): test-module_teal.R:1404:7, test-module_teal.R:1411:5,
test-module_teal.R:1414:5, test-module_teal.R:1673:5, test-module_teal.R:1731:5
[ FAIL 0 | WARN 0 | SKIP 6 | PASS 515 ]
```
> disable lockfile generation in `callr`, `testthat::tests` and `R CMD CHECK`

- tests/testthat/test-module_teal.R
Closes https://github.com/insightsengineering/coredev-tasks/issues/581
Adding maximum timeout to 500 seconds and change duration every 0.5 seconds when checking lockfile existence.
> increase timeout for ci

- .github/workflows/check.yaml
- .github/workflows/docs.yaml
- .github/workflows/release.yaml
- .github/workflows/scheduled.yaml
Possible because of https://github.com/insightsengineering/r.pkg.template/pull/252/files
> Run GitHub Actions with `setup-r-dependencies` installation strategy - - - - Bye Bye `staged-dependencies`

- DESCRIPTION
Since `renv` was released on CRAN on Oct 12 https://cran.r-project.org/web/packages/renv/index.html with the newest fix for the bug that we reported in here https://github.com/rstudio/renv/issues/2007 we can just vbump `renv` and use CRAN version instead of GitHub version.
> Use CRAN version of `renv`

- DESCRIPTION
- NEWS.md
- R/module_filter_data.R
- R/teal_data_utils.R
Partner to 
- https://github.com/insightsengineering/teal.data/pull/343 
- https://github.com/insightsengineering/teal.code/pull/214
Replace `teal.data::get_code()` (that worked on `teal_data()`) with `teal.code::get_code()` (that works on `qenv`).
> 210 substitute `teal.data::get_code` with `teal.code::get_code`

- R/module_init_data.R
- tests/testthat/test-module_teal.R
- tests/testthat/test-utils.R
Fixes #1398
- Should fix CI error in  https://github.com/r-universe/pharmaverse/actions/runs/11517110492/job/32061355783
> Fixes show r code reproducibility and CI

- R/module_filter_data.R
- R/module_init_data.R
This does not change any behavior of anything.
This is just consistency management with `#@linksto` tag that we have for `lockEnvironment(.raw_data)`
https://github.com/search?q=repo%3Ainsightsengineering%2Fteal+%23+%40linksto&type=code
> Unify `#@linksto` usage

- R/init.R
- R/module_teal.R
- R/module_teal_data.R
- R/utils.R
- man/check_modules_datanames.Rd
- tests/testthat/test-init.R
- tests/testthat/test-module_teal.R
Closes #1321 
Little refurnishment:
- splitted `check_modules_datanames` to two functions, one to return `character` and other to return `shiny.tag.list`
- Renamed related utilities to better fit to what they do.
> The documentation of `check_modules_datanames()`

- DESCRIPTION
Since we introduced `[.teal_data` we need to vbump dependencies of `teal.code` and `teal.data`
> Update versions of `teal.data` and `teal.code`

- .github/workflows/check.yaml
- .github/workflows/docs.yaml
- .github/workflows/release.yaml
- .github/workflows/scheduled.yaml
- tests/testthat/test-module_teal.R
Workflows are failing on main and on every PR as `rtables.officer` is not yet released on CRAN. 
`rtables.officer` is an indirect dependency via `teal.reporter`.
- Adds rtables and rtables.officer to `lookup-refs` on `setup-r-dependencies` workflow
> Fixes `setup-r-dependencies` by adding `rtables.officer`

- R/init.R
- R/module_init_data.R
- R/module_teal_data.R
- R/teal_reporter.R
- man/TealReportCard.Rd
- man/init.Rd
- man/module_init_data.Rd
- man/module_teal_data.Rd
Fixes #1420
With the package prefix `R CMD check` doesn't complain (with 2024-12-07 r87428 ucrt).
See https://github.com/insightsengineering/teal/issues/1420#issuecomment-2535506586 for a longer explanation on why this fixed the links issue.
> Fix documentation note about links on r-devel

- .pre-commit-config.yaml
- DESCRIPTION
- R/module_teal_data.R
- R/modules.R
- R/utils.R
- tests/testthat/test-modules.R
Fixes #1417 
- Replace styling in `format.module(s)` with `cli`
- Remove `strip_style` function in favor of `cli::ansi_strip`
- Reformat argument style in line with rest of file/package
- Forces text color to black on white background (relevant in dark mode)
- Align `transformators` in module print
> Uses `{cli}` instead of `{crayon}`

- vignettes/data-transform-as-shiny-module.Rmd
- vignettes/decorate-module-output.Rmd
- Change absolute paths to `insightsengineering.github.io/teal/...` to `fun_name()`
- downside:
- `knitr` keeps the inline code as is, so CRAN's vignettes don't have the links
- upside:
- pkgdown is smart to detect and create a link to the reference page (see within)
- `urlcheck` CI doesn't fail on `main` and PRs with unreleased code
- Articles in version-specific documentation don't suddenly take you to `latest-tag`
Using relative links (`../reference`), but this will break CRAN vignettes as well
> Fixes broken links by leveraging `pkgdown` autodetection of function use in inline code

- NEWS.md
- R/init.R
- R/module_bookmark_manager.R
- R/module_data_summary.R
- R/module_init_data.R
- R/module_teal.R
- R/module_teal_data.R
- R/module_teal_lockfile.R
- man/init.Rd
- man/module_bookmark_manager.Rd
- man/module_data_summary.Rd
- man/module_filter_data.Rd
- man/module_init_data.Rd
- man/module_teal.Rd
- man/module_teal_data.Rd
- man/module_teal_lockfile.Rd
- man/module_teal_module.Rd
- man/module_teal_with_splash.Rd
- man/module_transform_data.Rd
- deprecate id in init #1438  
- fixing (wrong) id documentation in inherited docs. Please notice that methods were inheriting `id` documentation from init. It means that all modules had a wrong description.
> deprecate id from init

- .github/workflows/scheduled.yaml
- DESCRIPTION
- NEWS.md
Part of https://github.com/insightsengineering/nestdevs-tasks/issues/98
> Fix CI pipelines

- R/init.R
Run this to see what happens
```r
library(teal.modules.general)
app <- teal::init(
data = teal_data() |> within(iris <- iris),
modules = modules(
tm_missing_data()
)
)
runApp(app)
```
> runApp can't work due to as.shinyapp.obj dispatch failure

- DESCRIPTION
Since new version of teal.reporter is on CRAN
it's a good moment to update teal, the reverse dependency,
so that we can run tests and see if all is passing for the newly released teal.repoter.
teal will be released anyway soon and dependencies would be bumped to releases versions
https://cran.r-project.org/web/packages/teal.reporter/index.html
> Update teal.reporter version

- R/init.R
- R/module_teal.R
- R/modules.R
- tests/testthat/test-module_teal.R
Part of #1450 as it provides better API for people who consume teal as a shiny module.
> Move the reporter module creation to `module_teal`

- .github/workflows/check.yaml
- .github/workflows/docs.yaml
- .github/workflows/release.yaml
- .github/workflows/scheduled.yaml
- DESCRIPTION
> vbump teal.data

- vignettes/adding-support-for-reporting.Rmd
- vignettes/data-as-shiny-module.Rmd
- vignettes/data-transform-as-shiny-module.Rmd
- vignettes/decorate-module-output.Rmd
- vignettes/getting-started-with-teal.Rmd
- vignettes/including-data-in-teal-applications.Rmd
Part of vignette review https://github.com/insightsengineering/nestdevs-tasks/issues/99
> Make sure the code chunks does not break because of warnings

- staged_dependencies.yaml
This addresses an error during staged.dependencies installation of `teal`:
```
File ./staged_dependencies.yaml invalid, field upstream_repos cannot be an array and must have entries repo, host
```
> fix: add missing staged.dependencies entry

- inst/css/sidebar.css
Companion of https://github.com/insightsengineering/teal.slice/pull/647
UI changes the following which address [this comment](https://github.com/insightsengineering/teal/pull/1507#issuecomment-2818676604):
- The Active data summary, Filter Data, and Transform data accordions headers use primary colors (blue default).
- The padding inside the accordion body is removed
- The gap between the three accordions is reduced
> Improve the teal sidebar

- R/module_nested_tabs.R
- R/teal_reporter.R
When teal_module's server returns an error (validation error, qenv error etc.) teal.reporter-add button has no protection against it. This PR fixes following:
- To not display error received from a module
- To disable add-to-report-button when error occurs
> Disable report when error

- R/module_init_data.R
On teal.code@main `get_var` is hard-deprecated. Here is the easier way to obtain qenv objects as a list
> obtain a named list from environment

- R/module_teal.R
Tested with 
- https://github.com/insightsengineering/teal.reporter/discussions/388
Fixes this point
from this comment https://github.com/insightsengineering/nestdevs-tasks/issues/106#issuecomment-3241994959
Previously we created new reporter when setting id, instead of reusing the reporter.
Now you are able to pass custom reporter that is used across the app.
> If reporter was provided, reuse it in srv_teal

- R/module_nested_tabs.R
- R/zzz.R
- vignettes/teal-options.Rmd
Adds a new option `teal.sidebar.position` which can move the main teal sidebar to left/right with left being the default when nothing is specified.
```
devtools::load_all("teal")
options(teal.sidebar.position = "right")
init(data = teal_data(iris = head(iris)), modules = example_module()) |> runApp()
```
> Add option to move sidebar to the right

- R/modules.R
- man/teal_modules.Rd
The description is wrong after latest release. I'm removing the description of the `teal_modules` fields as it might inspire users to use it.
> delete wrong @return
