NEWS.md
R/module_nested_tabs.R
R/modules.R
man/module.Rd
tests/testthat/test-module_nested_tabs.R

related to https://github.com/insightsengineering/teal.slice/issues/64
Append `filter_panel_api` argument to the list of arguments in `srv_nested_tabs.teal_module`.

filter_panel_api

---

vignettes/creating-custom-modules.Rmd

Part of https://github.com/insightsengineering/teal.slice/issues/76

Remove _FILTERED

---

tests/testthat/test-get_rcode.R

closes https://github.com/insightsengineering/coredev-tasks/issues/427

fix failing tests on R 4.3

---

R/module_tabs_with_filters.R

linked to https://github.com/insightsengineering/teal.slice/pull/254

filterable

---

DESCRIPTION
NEWS.md

Releasing 0.13.0
Linking with:
https://github.com/insightsengineering/nestdevs-tasks/issues/24

release 0.13.0 [skip vbump]

---

R/teal_slices.R
man/teal_slices.Rd

this fixes https://github.com/insightsengineering/teal.slice/issues/355

355 rename module_add to allow_add

---

DESCRIPTION

needed to deploy newest teal to r-universe

fix r-universe deployment

---

DESCRIPTION
NEWS.md

Releasing 0.14.0
Linking with:
https://github.com/insightsengineering/nestdevs-tasks/issues/25

release 0.14.0 [skip vbump] [skip spelling]

---

NEWS.md
inst/css/custom.css

this fixes https://github.com/insightsengineering/teal/issues/893
Demo
https://github.com/insightsengineering/teal/assets/6700955/8def3b74-b747-4df0-8434-4dde85f484cf

Application header goes below horizontal line upon resizing

---

.Rbuildignore
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/question.yml
DESCRIPTION
README.md
man/teal-package.Rd

Related to https://github.com/insightsengineering/coredev-tasks/issues/462

readme updates

---

R/module_teal_with_splash.R

companion to [this PR](https://github.com/insightsengineering/teal.data/pull/167)

ddl alternative

---

R/teal_slices.R
man/teal_slices.Rd

Related to [this issue](https://github.com/insightsengineering/teal.slice/issues/479).

479 improve documentation

---

vignettes/adding-support-for-reporting.Rmd

part of https://github.com/insightsengineering/teal.code/pull/176

`get_code` to return concatenated code string 

---

vignettes/adding-support-for-reporting.Rmd
vignettes/creating-custom-modules.Rmd
vignettes/data-as-shiny-module.Rmd

adapted example modules to follow `example_module`

update example modules in vignettes

---

R/module_nested_tabs.R
R/modules.R
R/modules_debugging.R
man/dot-datasets_to_data.Rd
man/eval_code.Rd
man/filter_calls_module.Rd
man/module.Rd
man/within.teal_data_module.Rd

Changes `tdata` to `teal_data` in a few places we missed.

remove leftover `tdata` mentions

---

R/get_rcode_utils.R

Close #985 associated with https://github.com/insightsengineering/teal.data/pull/223

985 get_code_dependency check_names=FALSE

---

R/utils.R
tests/testthat/test-utils.R

This comment was omitted https://github.com/insightsengineering/teal/pull/1004/files/0596deeb4575a6c0ac6f6c2251054303ccc500fb#r1427716753
during https://github.com/insightsengineering/teal/pull/1004
@kartikeyakirar would you mind reviewing ?

999 change names(teal_data) to ls(get_env(teal_data))

---

R/module_nested_tabs.R
R/module_tabs_with_filters.R
R/utils.R

closes https://github.com/insightsengineering/teal/issues/1029

include parent datasets to the modules

---

_pkgdown.yml

restore "get started"

---

NEWS.md
R/init.R
R/teal_slices.R
R/utils.R
man/init.Rd
man/srv_teal_with_splash.Rd
man/teal_slices.Rd
man/ui_teal_with_splash.Rd
tests/testthat/test-init.R

1031 drop list support

---

DESCRIPTION
NEWS.md
man/reporter_previewer_module.Rd
man/teal-package.Rd

[skip vbump] patch release 0.15.1

---

R/module_teal.R
R/modules_datasets.R

Substituting `module_datasets()` with `modules_datasets()`

using `modules_datasets()`

---

R/TealAppDriver.R
man/TealAppDriver.Rd

```r
app <- TealAppDriver$new(); app$open_url()
```
opens a browser with the app running.

503 `$open_url` method for `TealAppDriver`

---

R/TealAppDriver.R

update wait time to 5 secs

---

R/TealAppDriver.R

Part of https://github.com/insightsengineering/coredev-tasks/issues/503
- Corrects typo

Fixes bug on set_module_input

---

README.md

add link to the video

---

DESCRIPTION
R/init.R
R/module_teal.R
R/teal_lockfile.R
man/teal_lockfile.Rd

most of my code review comments
please note that the target is a feature branch

479 mirai pr

---

R/utils.R
tests/testthat/test-utils.R

one step closer towards consistent error / warning message when checking classes

get_teal_bs_theme(): use checkmate for throw and check

---

vignettes/decorate-module-output.Rmd

Still working on this example as the final module does not produce the plot

Update decorators vignette for multiple decorators

---

.github/workflows/scheduled.yaml
DESCRIPTION

Tries to reduce some package versioning complexity in CI pipelines. More explanation in here https://github.com/insightsengineering/teal.slice/pull/637#issuecomment-2607373951

Simplify CI Pipelines

---

DESCRIPTION

As we are planning to release teal, at some point we should update all versions of development dependencies to their released versions

vbump logger

---

DESCRIPTION

Similar to PRs where we updated teal.logger and teal.reporter after their release on CRAN
- https://github.com/insightsengineering/teal/pull/1463
- https://github.com/insightsengineering/teal/pull/1462

Update teal.code version

---

vignettes/data-transform-as-shiny-module.Rmd

Part of https://github.com/insightsengineering/nestdevs-tasks/issues/99

Review transformator vignette

---

DESCRIPTION

Vbumps teal.widgets to the newest version

vbump teal.widgets

---

DESCRIPTION

So that teal is prepared for it's upcoming release

vbump teal.slice

---

R/module_transform_data.R

Raise a shiny silent error when data is NULL

---

R/dummy_functions.R

fixes #1494 
RHUB workflow https://github.com/insightsengineering/teal/actions/runs/13372139467

1494 fix note

---

DESCRIPTION
NEWS.md
R/dummy_functions.R
R/init.R
R/landing_popup_module.R
R/module_teal_with_splash.R
R/show_rcode_modal.R
R/tdata.R
R/utils.R
man/init.Rd
man/module_teal_with_splash.Rd
tests/testthat.R

Hey @vedhav @gogonzo just letting you know that I am merging `main` into `test@bslib@main` branch, so that on other repositories, like `tmg`, we can install `teal` from this branch and also we can satisfy condition for `teal` to be `>= 0.16.0`.
https://github.com/insightsengineering/teal.modules.general/blob/report_redesign_poc%40main/DESCRIPTION#L83
https://github.com/insightsengineering/teal.modules.general/blob/report_redesign_poc%40main/DESCRIPTION#L30

Merge main to test@bslib@main

---

NEWS.md

Part of  #1500
Remove the incorrect changelog line from our docs.

Remove incorrect changelog item (2/2)

---

R/module_data_summary.R
R/module_teal.R
inst/css/custom.css
inst/css/sidebar.css

Final UI and bslib changes

---

R/module_snapshot_manager.R

Small PR to update snapshot manager button title

update snapshot manager button title

---

R/teal_reporter.R

Companion to https://github.com/insightsengineering/teal.reporter/pull/326

Improves `ReportDocument` editor

---

DESCRIPTION

Fixes https://github.com/insightsengineering/teal/issues/1532
Workflows
- 1 https://github.com/insightsengineering/teal/actions/runs/15777388018

fix scheduled jobs

---

DESCRIPTION
man/teal-package.Rd

added nina

---

DESCRIPTION

Update DESCRIPTION for r-lib/mirai and r-lib/nanonext

---

R/TealAppDriver.R

Fixes the broken test here: https://github.com/insightsengineering/teal.goshawk/pull/355

Fix `TealAppDriver` namespace due to changes in tab navigation

---

DESCRIPTION
NEWS.md
man/check_reactive.Rd

Closes #1528
* Update DESCRIPTION, bumps all teal.* dependencies
* Update NEWS

[skip vbump] upversion v1.0.0

---

R/module_teal.R
tests/testthat/test-shinytest2-reporter.R

Show/Hide reporter UI when teal UI is generated by `renderUI`
